### ISSUE TITLE
Trouble to understand not(p) parser

### ISSUE THREAD

**Issue by pbadenski** [robey/packrattle#16]
I am bit confused about the `not(p)` parser.

I'm not sure why  `P.repeat(P.not(P.string("\"")))` doesn't work, but`P.repeat(P.regex(/[^"]/))` does. Perhaps this could be clarified in the documentation?

**Comment by robey** [comment]
Thanks, I've made a note to clarify that `check` and `not` are really assertions, and can't make forward progress.

Basically, `repeat(not(string))` means "continue asserting that this string isn't here". It doesn't move the parser forward.

The regex `[^"]` means "match any character that isn't a quote", so as long as it sees non-quote characters, it succeeds and moves forward. You could get a similar effect by moving the repeat into the regex: `[^"]*`
