### ISSUE TITLE
Fixpoint combinator

### ISSUE THREAD

**Issue by maxxk** [robey/packrattle#7]
Is it possible to add fixed-point combinator for parsers?
This combinator would be useful in languages like purescript which don't support recursive data definitions.

To illustrate the proposal we can rewrite recursive example from readme in this way:
```javascript
var expr = pr.fix(function(expr) { 
    return pr.alt(
        pr.seq(expr, "+", expr),
        pr.regex(/\d+/).onMatch(function (m) { return m[0]; }));
})
```

**Comment by robey** [comment]
forgot to close this bug when I merged the branch. :)
